# Generated by Django 5.1.4 on 2024-12-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='jahon', max_length=100),
            preserve_default=False,
        ),
    ]
